📚 Add kdoc for Square.* and Testing.*
jmfayard/refreshVersions pull request #236
Opened 2020-08-29 10:27 UTC by jmfayard

2020-08-29 21:10 UTC, jmfayard commented
do not merge yet, will continue later

2020-09-01 16:14 UTC, jmfayard commented
ready for review

2020-09-10 23:27 UTC, LouisCAD requested changes
I've already started correcting the style to be consistent, and addressing other comments I made.

I'll merge this once I'm done with it (will happen before Monday).

2020-09-10 23:27 UTC, LouisCAD commented on plugins/dependencies/src/main/kotlin/dependencies/Kotlin.kt
> +     * https://kotlinlang.org/api/latest/kotlin.test/kotlin.test/
These dangling links are not clickable in the IDE. Let's avoid that and always have text setting expectations on what the link is about.

2020-09-10 23:27 UTC, LouisCAD commented on plugins/dependencies/src/main/kotlin/dependencies/CashApp.kt
> +     * - [CHANGELOG](https://github.com/cashapp/sqldelight/blob/master/CHANGELOG.md)
The style here is inconsistent with the existing dependency notations KDoc that can be found in the `Square` object.

Having a consistent style makes a better impression on users and values the effort in making the whole project right.

Happy to improve the style, but we need to discuss it and agree on a style to stick with.
I'll complete a contributing guide covering this as we might welcome further contributions there from the community, and we might forget about it ourselves.

I'm not repeating this comment to all the other KDocs in this PR, this one stands for them all.

2020-09-10 23:27 UTC, LouisCAD commented on plugins/dependencies/src/main/kotlin/dependencies/KotlinX.kt
> +     * - https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.reflect/
Dangling links

2020-09-10 23:27 UTC, LouisCAD commented on plugins/dependencies/src/main/kotlin/dependencies/Orchid.kt
> +     * https://orchid.run/plugins - Orchid plugins
Dangling link

2020-09-10 23:27 UTC, LouisCAD commented on plugins/dependencies/src/main/kotlin/dependencies/Orchid.kt
> + * - https://orchid.run/plugins - Orchid plugins
Dangling link

2020-09-10 23:27 UTC, LouisCAD commented on plugins/dependencies/src/main/kotlin/dependencies/Square.kt
> +     * - [Consuming APIs with Retrofit | CodePath Android Cliffnotes](https://guides.codepath.com/android/Consuming-APIs-with-Retrofit#references)
We don't control how outdated a third-party article can become, yet, we are helping our users update (diverging further from these possibly outdated articles at a quicker rate).

Also, we might never find the best article on a library, so let's stick to the official and blog posts from authors and major contributors, and for the rest, or when official content is lacking, let the users decide what to look for as a reference based on the metrics they value like time of publication, programming language (Kotlin vs Java), platform (Android, JVM, other…), search engines and critical sense do a great job for that.

2020-09-14 00:51 UTC, LouisCAD approved these changes

2020-09-14 00:53 UTC, LouisCAD commented
@jmfayard Feel free to review the changes I just pushed and merge once the CI is done running the checks.

2020-09-14 05:34 UTC, merged