github actions: staging website
jmfayard/refreshVersions pull request #308
Opened 2020-12-11 16:01 UTC by jmfayard

https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables

2020-12-12 23:30 UTC, LouisCAD commented on mkdocs.yml
> +  - 'Gradle buildSrcVersions': gradle-buildsrcversions.md
This change is unrelated to this PR (out of the scope), plus we previously agreed that we would not make it part of the main menu for now.

2020-12-12 23:32 UTC, LouisCAD requested changes

2020-12-12 23:32 UTC, LouisCAD commented on mkdocs.yml
> +  - 'Gradle buildSrcVersions': gradle-buildsrcversions.md
This change is unrelated to this PR (out of the scope), plus we previously agreed that we would not make it part of the main menu for now.

2020-12-12 23:32 UTC, LouisCAD commented on site.sh
> +#    site.sh release      # publish to https://jmfayard.github.io/refreshVersions/
The word "site" lacks explicitness about what it actually does.

I think this should be split into two scripts:
1. `build-website.sh`
2. `publish-website.sh`

The `publish-website.sh` script would:
1. Require a branch name to be passed as an argument.
2. Run the `build-website.sh` script.
3. Publish it at the right place.

2020-12-13 08:13 UTC, jmfayard commented
the GitHub actions do not even run for unknown reasons so I gave up on this pull request

2020-12-13 08:41 UTC, jmfayard commented
marked as draft

2021-05-17 09:54 UTC, closed without merging