Dependency Notation for Horologist.
jmfayard/refreshVersions pull request #564
Opened 2022-07-16 14:47 UTC by yschimke

## What?

Resolves #563

Adds dependency notation for https://github.com/google/horologist

## Why?

Trying out refreshVersions for my Wear app development, and these libraries are likely to be required for most properly implemented wear apps.

## How?

Followed instructions page https://jmfayard.github.io/refreshVersions/contributing/submitting-prs/dependency-notations-updates/ and the approach used by Accompanist.

## Testing?

Ran gradle test command.

2022-07-19 17:12 UTC, jmfayard commented on plugins/dependencies/src/test/resources/dependencies-versions-key-validated.txt
> +com.google.android.horologist..horologist-tiles=version.NO-RULE
see here for the version

2022-07-19 17:13 UTC, jmfayard requested changes
Thanks for your contribution! Left some comments

2022-07-19 17:13 UTC, jmfayard commented on plugins/dependencies/src/main/kotlin/dependencies/Google.kt
> +    object Horologist : DependencyGroup(group = "com.google.android.horologist") {
Missing a rule, see file dependencies-versions-key-validated.txt

Shouuld be something like this:

```
        rawRules = """
            com.google.android.horologist:*
                ^^^^^^^        ^^^^^^^^^^
        """.trimIndent()
```

2022-07-19 17:13 UTC, jmfayard commented on plugins/dependencies/src/main/kotlin/dependencies/Google.kt
> +        val composables = module("horologist-composables")
Can you put this module and the two others at line 638 and 640 first?

2022-07-19 17:13 UTC, jmfayard commented on plugins/dependencies/src/main/kotlin/dependencies/Google.kt
> +        object Compose : DependencyGroup(group = "com.google.android.horologist") {
Missing `val compose = Compose` no?

2022-07-27 10:22 UTC, jmfayard commented
Merged, great job, thank you! 🙏🏻

2022-07-27 10:22 UTC, jmfayard approved these changes

2022-07-27 10:22 UTC, merged

2022-07-27 11:13 UTC, LouisCAD commented
Nicely done, and right from the library authors, thank you! 🙌🙏